server:
  port: 9099

spring:
  application:
    name: @pom.artifactId@

    # Druid 数据库连接池分配
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    # 初始化连接大小[0]
    druid:
      initial-size: 1
      # 最小空闲连接数[0]
      min-idle: 1
      # 最大连接数[8]
      max-active: 20
      # 配置获取连接等待超时的时间(毫秒)[-1]
      max-wait: 60000
      # 查询超时时间(秒)
      query-timeout: 90

      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 'x'
      # 申请连接时检测连接可用性[false]
      test-on-borrow: false
      # 归还连接检测[false]
      test-on-return: false
      # 超时是否检测连接可用性[true]
      test-while-idle: true

      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接 (毫秒)
      time-between-eviction-runs-millis: 60000
      #  配置一个连接在池中最小生存的时间(毫秒，默认30分钟)
      min-evictable-idle-time-millis: 300000
      # 通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat；日志用的filter:log4j；防御sql注入的filter:wall
      filters: stat,wall,slf4j
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

      # 是否缓存PreparedStatement. PSCache对支持游标的数据库性能提升巨大，比如说oracle.在mysql下建议关闭.
      pool-prepared-statements: false
      # 每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20

      # StatViewServlet [https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE]
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 监控页面的用户名和密码
        login-username: admin
        login-password: admin
        reset-enable: false

      # StatFilter [https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter]
      filter:
        stat:
          db-type: mysql
          #慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 2000
          # SQL合并
          merge-sql: false

        # WallFilter [https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE-wallfilter]
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
    # druid配置结束
    # #################################

#mybatis配置
#映射文件的路径，支持Ant风格的通配符，多个配置可以使用英文逗号隔开
mybatis:
  mapper-locations: classpath*:**/*Mapper.xml
  #类型别名包配置，只能制定具体的包，多个配置可以用英文逗号隔开
  #type-aliases-package: =**.dao
  #自动将以下画线方式命名的数据库列映射到java对象的驼峰式命名属性中。默认为false
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.cloud.gateway: debug